name: Build Kernel with KSU-Next

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          ref: mt6878/Galaga/v
          submodules: 'recursive'
          fetch-depth: 1

      - name: Setup KernelSU-Next
        run: |
          echo "=== Patching KernelSU-Next ==="
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/dev/kernel/setup.sh" | bash -   # ← исправленный путь

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@v1.10.0
        with:
          kernel-url: .
          kernel-branch: mt6878/Galaga/v
          defconfig: gki_defconfig
          clang: aosp
          anykernel3: true
          # ksu и ksu-other убираем, потому что патчим вручную выше
